logging:
  level:
    root: INFO
server:
  port: 8081
spring:
  application:
    name: companies
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:companiesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password