spring:
  application:
    name: pokemon
  datasource:
    url: jdbc:h2:mem:pokemondb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  # Same than the configuration on the bean
  #cache:
  #  type: caffeine
  #  cache-names: pokemonCollection # Define los nombres de las cachés que se van a gestionar
  #  caffeine:
  #    spec: expireAfterWrite=24h # Configura la expiración después de escribir para todas las cachés mencionadas

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
